### ISSUE TITLE
'utf-8' codec can't decode byte 0xec in position 69: invalid continuation byte

### ISSUE THREAD

**Issue by AdamGrumlik** [ondrejvysek/HomeAssistant-CEZDistribuce-PND#1]
Ahoj, v /homeassistant/appdaemon/apps/pnd/*.csv mám chybu:
'utf-8' codec can't decode byte 0xec in position 69: invalid continuation byte
čím to může být?

Děkuji.

**Comment by ondrejvysek** [comment]
Soubory jsou kodované v latin1 a File editor je neumí korekně zobrazit - zkusit stáhnout a zobrazit mimo File file editor (Notepad, Notepad++ či jiné). Vidím tam to samé, nicméně vše funguje jak má.

**Comment by AdamGrumlik** [comment]
> Soubory jsou kodované v latin1 a File editor je neumí korekně zobrazit - zkusit stáhnout a zobrazit mimo File file editor (Notepad, Notepad++ či jiné). Vidím tam to samé, nicméně vše funguje jak má.

OK, děkuji. Stáhl jsem a data tam jsou, takže skvělé.
