### ISSUE TITLE
Měsíční agregace - data

### ISSUE THREAD

**Issue by matomatusov** [ondrejvysek/HomeAssistant-CEZDistribuce-PND#15]
Ahoj, bolo by možné aby daný graf zobrazoval udaje od začiatku kalendárného mesiaca? Napr. od 1.3 do 31.3 2024

![1](https://github.com/ondrejvysek/HomeAssistant-CEZDistribuce-PND/assets/129114957/eb50a5c8-237f-4ac5-ba9c-cd1f4dd6ad32)

Dik moc.

**Comment by ondrejvysek** [comment]
v definici grafu změnit
```
span:
  end: day
```
za
```
span:
  end: week
```
Výsledek je lepší, nicméně ne dokonalý - zarovnává dle období dat, tj pokud interval není na začátku resp konce měsíce, nebude úplně přesné. Dosáhnout by se toho dalo (teoreticky), kdyby se dale end: month, ale Apex má evidentně problém s přestupným rokem a ukazuje nesmyls. 

Do nábodu jsem dal ten week.
