### ISSUE TITLE
Posun datumu výroby/spotřeby

### ISSUE THREAD

**Issue by michalchot** [ondrejvysek/HomeAssistant-CEZDistribuce-PND#28]
Ahoj, zjistil jsem, že se mi o jeden den "předbíhá" datum v naměřených datech. Zkrátka dnes 30.5.24 mám v grafu už hodnotu spotřeby/výroby na 31.5.24. Kde může být chyba?
![obrázek_2024-05-30_072916922](https://github.com/ondrejvysek/HomeAssistant-CEZDistribuce-PND/assets/78978644/0bc8a18e-4ac4-4ca5-afda-49234d2470be)

Díky

**Comment by ondrejvysek** [comment]
viz [](https://github.com/ondrejvysek/HomeAssistant-CEZDistribuce-PND/issues/22) aneb musíme si počkat na opravu na straně PND
Dotaz:
Správnost dat – porovnával jsem data (23.5.2024 16:50) A+ (stejná situace je i u A-) a nesouhlasí správnost pokud zvolím vlastní období tak se data liší:
a. V tabulkovém výpisu je vše správně, stejně tak když se zvolí období „dnes“
b. V exportu (XLSX / CSV) se poslední datum ukazuje v následujícím dni – viz obrázek níže. Jak prosím zajistit, aby oba výstupy byly identické? Všiml jsem si rozdílu kdy v tabulce je datum a 24:00, kdežto v exportu je datum a 0:00. nicméně dnešní data nemohou být zítra 😊
(obrázek stejný jako výše)

Odpověď:
Bohužel, o této chybě víme a dodavatel pracuje na odstranění. V případě exportování dat ve 1/4h profilu k problému nedochází. Za komplikace se omlouváme.
