### ISSUE TITLE
Dotaz: kde najít Token?

### ISSUE THREAD

**Issue by noreithe** [ondrejvysek/HomeAssistant-CEZDistribuce-PND#30]
Ahoj, poprosil bych o nějaký screenshot, kde hledat položku pro vytvoření tokenu, zmíněné nikde nevidím:

"Klikněte na vaše jméno vlevo dole
Klikněte na záložku "Zabezpečení" nahoře"

Předem díky moc.

**Comment by matomatusov** [comment]
Ahoj, @noreithe  snáď pomože.

![1](https://github.com/ondrejvysek/HomeAssistant-CEZDistribuce-PND/assets/129114957/a0fbec70-16f1-4e09-81d1-4a7e3b0a3d83)

**Comment by noreithe** [comment]
Jo takhle, diky moc :)

**Comment by ondrejvysek** [comment]
Díky @matomatusov. @noreithe  v návodu je také, ne tak hezky :) [https://github.com/ondrejvysek/HomeAssistant-CEZDistribuce-PND/raw/main/obrazky/02-hatoken.png](https://github.com/ondrejvysek/HomeAssistant-CEZDistribuce-PND/raw/main/obrazky/02-hatoken.png)
