### ISSUE TITLE
Nenčítají se hodnoty z PND

### ISSUE THREAD

**Issue by Rotif** [ondrejvysek/HomeAssistant-CEZDistribuce-PND#32]
Ahoj,
z webu čezu se mi nenačtou žádné hodnoty.
V logu se vždy po spuštění automatizace zobrazuje:
2024-06-01 00:30:56.650143 WARNING pnd: Coroutine (<coroutine object ADAPI.set_state at 0x7f88c30a90>) took too long (10 seconds), cancelling the task...
Přitom ale v složce pnd jsou screenshoty, které zobrazují volbu elektroměru a hodnot na PND.
Co dělám špatně?
Dík

**Comment by ondrejvysek** [comment]
Prosim:
1. Jakym screenshotem to konci? Jsou cislovane
2. Prosim o vic logu z appdaemon. Skript se evidentne spusti, tak v logu musi byt detail

**Comment by Rotif** [comment]
Screenshoty z pnd log, víc nevím, kde bych hledal:
![00](https://github.com/ondrejvysek/HomeAssistant-CEZDistribuce-PND/assets/114533831/e23165ae-b9a1-49ef-8fae-68c5b7c61c50)
![01](https://github.com/ondrejvysek/HomeAssistant-CEZDistribuce-PND/assets/114533831/54e52f3a-9db6-4f6e-8120-c3fe8fb6e5df)
![02](https://github.com/ondrejvysek/HomeAssistant-CEZDistribuce-PND/assets/114533831/6864b8e0-f54e-4024-a936-8afbf6aad08e)
![03](https://github.com/ondrejvysek/HomeAssistant-CEZDistribuce-PND/assets/114533831/9bca3d49-6799-48e1-acf5-d00a8dd5652e)
![03-0-a](https://github.com/ondrejvysek/HomeAssistant-CEZDistribuce-PND/assets/114533831/dbb1c6da-ec86-4a7c-aca9-b5aa3b522023)
[debug-ELM.txt](https://github.com/user-attachments/files/15523224/debug-ELM.txt)
[pnd.log](https://github.com/user-attachments/files/15523225/pnd.log)

**Comment by ondrejvysek** [comment]
Kouknu na to, logy appdaemon jsou v doplnku appdaemon, nahore je zalozka log, tak tam. Jak prosim vypada apps.yaml? Predevsim ELM

**Comment by Rotif** [comment]
V příloze log a apps
[log appdaemon.txt](https://github.com/user-attachments/files/15524481/log.appdaemon.txt)

[apps_yaml.txt](https://github.com/user-attachments/files/15524484/apps_yaml.txt)
Dík

**Comment by Rotif** [comment]
Omlouvám se, zadal jsem chybné číslo elektroměru, opravím to a dám vědět.

**Comment by ondrejvysek** [comment]
Super, on to píše i ten log, že nenalezl ELM:
```
  File "/homeassistant/appdaemon/apps/pnd.py", line 294, in run_pnd
    raise Exception(f"Failed to find '{self.ELM}' in the selection")
Exception: Failed to find '37120345' in the selection
```
