### ISSUE TITLE
Unexpected error in worker for App pnd

### ISSUE THREAD

**Issue by MarCa123456** [ondrejvysek/HomeAssistant-CEZDistribuce-PND#41]
Po instalaci se mi nevytvořily tyto tři senzory
![image](https://github.com/ondrejvysek/HomeAssistant-CEZDistribuce-PND/assets/130635004/0c6a1384-1844-4f4d-8e13-bfc54cacb7be)

Při běhu PND.py je v logu tato chyba
![image](https://github.com/ondrejvysek/HomeAssistant-CEZDistribuce-PND/assets/130635004/5d157ce8-8f13-4072-b6f4-bd6c01bb8e28)

**Comment by ondrejvysek** [comment]
Co mate prosim za verzi skriptu? (Prvni radek). Toto by melo byt v aktualni verzi osetrene.

**Comment by MarCa123456** [comment]
ver = "0.9.7"
________________________________

**Comment by ondrejvysek** [comment]
Je tam aktualizace, ktera by to mela vyresit. Prosim o test a info, zdali zabralo. Diky

**Comment by MarCa123456** [comment]
Dobry den,

V mezicase jsem skoncil na problemu popsanem v tomto vlakne

Chyba v Numpy
 #42

Takze pockam az se vyresi toto a dam vedet.
________________________________

**Comment by ondrejvysek** [comment]
Reseni je v tom vlakne, je nutne pridat rucne starsi verzi numpy.

Aktualizace dokumentace dnes odpoledne

**Comment by MarCa123456** [comment]
Děkuji. Mohu potvrdit, že problém je nyní vyřešen. Data stažena. Všechny senzory vytvořené tak jak mají. Jen mám teď nějaká nesmyslná data v grafech, jak jsem pustil toho AppDeamona vícekrat za den.
Jdu se podívat jak to promazat. Pokud máte nějaký nápad budu moc rád.

**Comment by ondrejvysek** [comment]
V tuto chvíli počkat, za den zmizí
