### ISSUE TITLE
Chyba v Numpy

### ISSUE THREAD

**Issue by jankorous** [ondrejvysek/HomeAssistant-CEZDistribuce-PND#42]
Pro prvotní instalaci a nastavení podle Readme.md mi zůstává následující chyba:

```
2024-06-17 10:44:19.882820 WARNING AppDaemon: error loading plugin: HASS - ignoring
2024-06-17 10:44:19.883329 WARNING AppDaemon: ------------------------------------------------------------
2024-06-17 10:44:19.891036 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/plugin_management.py", line 140, in __init__
    mod = __import__(full_module_name, globals(), locals(), [module_name], 0)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/plugins/hass/hassplugin.py", line 14, in <module>
    from deepdiff import DeepDiff
  File "/usr/lib/python3.11/site-packages/deepdiff/__init__.py", line 10, in <module>
    from .diff import DeepDiff
  File "/usr/lib/python3.11/site-packages/deepdiff/diff.py", line 18, in <module>
    from deepdiff.helper import (strings, bytes_type, numbers, uuids, times, ListItemRemovedOrAdded, notpresent,
  File "/usr/lib/python3.11/site-packages/deepdiff/helper.py", line 63, in <module>
    np_float_ = np.float_
                ^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/numpy/__init__.py", line 397, in __getattr__
    raise AttributeError(
AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use `np.float64` instead.

2024-06-17 10:44:19.891424 WARNING AppDaemon: ------------------------------------------------------------
```

AppDeamon mám podle vzoru.

**Comment by ondrejvysek** [comment]
na jaké platformě to běží?
jak vypadá appdaemon.yaml?
jak vypadá konfigurace modulů AppDaemon?
Jaká je verze HA a verze AppDaemon?

Tohle je chyba někde mezi appdaemon a HA.

**Comment by jankorous** [comment]
AppDaemon.yaml:

```
---
appdaemon:
  latitude: 52.379189
  longitude: 4.899431
  elevation: 2
  time_zone: Europe/Amsterdam
  thread_duration_warning_threshold: 60
  plugins:
    HASS:
      type: hass
      ha_url: http://192.168.1.242:8123
      token: tádýdádýdá
  app_dir: /homeassistant/appdaemon/apps
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:
logs:
  pnd:
    name: pnd
    filename: /homeassistant/appdaemon/pnd.log
```

apps.yaml:
```
secrets: /homeassistant/secrets.yaml
pnd:
  module: pnd
  class: pnd
  log: pnd
  PNDUserName: !secret pnd_login
  PNDUserPassword: !secret pnd_password
  DataInterval: "01.06.2023 00:00 - 31.06.2024 00:00"
  ELM: "890971"
  DownloadFolder: "/homeassistant/appdaemon/apps/pnd"
```

Core je 2024.6.3 a běží na Rpi 4B 8GB.

Nastavení je takto:
![Snímek obrazovky 2024-06-17 v 18 45 34](https://github.com/ondrejvysek/HomeAssistant-CEZDistribuce-PND/assets/80398176/13cdea31-ca34-4991-b39f-92bdc62eb0f6)

**Comment by ondrejvysek** [comment]
Vypadá normálně. Můžete zkusit restart celého RPi? Občas tam vytuhne nějaká aktualizace. Ale tohle evidentně nestartuje kontejner s AppDaemonem :(

**Comment by jankorous** [comment]
I po restartu chyba zůstává a data netečou... 🫣 jako je to jen warning, ale nevypadá, že by se spouštěl.

**Comment by ondrejvysek** [comment]
Snip logu by se nenasel? Skript se nepousti sam od sebe, je nutna ta automatizace

**Comment by jankorous** [comment]
No to mám jako automatizaci, viz návod:
```
alias: Run PND
description: ""
trigger:
  - platform: time
    at: "00:30:00"
condition: []
action:
  - event: run_pnd
    event_data: {}
mode: single
```

**Comment by jankorous** [comment]
Tady ještě konec logu

[a0d7b954_appdaemon_2024-06-17T18-21-37.011Z.log](https://github.com/user-attachments/files/15875440/a0d7b954_appdaemon_2024-06-17T18-21-37.011Z.log)

**Comment by ondrejvysek** [comment]
Chyba je porad stejna, cetl jsem vic, napadlo me - zkusit dat prihlasovaci udaje primo do apps.yaml a vyhodit ten secret radek.

Ono to vypada, ze to ma za dalsi aplikaci a muze to na tom umrit. 

Pokus

**Comment by jankorous** [comment]
To už jsem tak zkoušel - dat login a pass na přímo, stejná issue 🫣

**Comment by jankorous** [comment]
Jj, restartuju pokaždé

**Comment by jankorous** [comment]
V GUI toho AppDaemona mám něco vidět?

**Comment by ondrejvysek** [comment]
na portu :5050 jeportál appdaemonu, ale tam asi nic nebude, když nestartuje. lze skusit komplet vyčistit apps.yaml, aby byl prázndý? aby zkusil nastartovat bez ničeho
![image](https://github.com/ondrejvysek/HomeAssistant-CEZDistribuce-PND/assets/29834082/60ded71b-a9bf-4f21-854a-a29b33b834ac)

**Comment by ondrejvysek** [comment]
Problém izolován (a projevuje se i v jiných instalacích), jenom nemá rychlé řešení. Někdy v uplynulých dnech došlo k aktualizaci buď Numpy nebo DeeDiff, které jsou podkladovým modulem pro Pandas (čte CSV). Díky této chybě nenaběhne AppDaemon správně a skript nemůže fungovat. Chyba je komplet mimo moji kontrolu.

Zkusím přepsat část s Pandas na jinou komponentu, jenom to nebude dnes, zkusím co nejdřív.

**Comment by ondrejvysek** [comment]
Pouze pro referenci a ladeni problemu https://github.com/pandas-dev/pandas/issues/59023

**Comment by ondrejvysek** [comment]
Včera (16.6.24) byla vydána verze Numpy 2.0.0 která zásadně mění funkcionalitu, Pandas si s ní zatím nepovída. Je nutné, nežli bude Pandas aktualizovaný používat Numpy 1.26.4. V nastavení AppDaemon je nutné přidat Python `package numpy==1.26.4`
![image](https://github.com/ondrejvysek/HomeAssistant-CEZDistribuce-PND/assets/29834082/c9bd5dbf-06f7-4bdc-b545-5ab745f697e8)

**Comment by jankorous** [comment]
Nice solution, PND se dostalo znatelně dál, nicméně se akce nedaří stáhnout nějaké csv:

```
link 07 Profil spotřeby za den (+A)
link 08 Profil výroby za den (-A)
```

a přijde mi, že po nestažení csv už nezpracuje data nebo se zastaví? Přikládám log.

[a0d7b954_appdaemon_2024-06-18T05-12-36.356Z.log](https://github.com/user-attachments/files/15880926/a0d7b954_appdaemon_2024-06-18T05-12-36.356Z.log)

**Comment by ondrejvysek** [comment]
To je asi stejna chyba jako zde https://github.com/ondrejvysek/HomeAssistant-CEZDistribuce-PND/issues/39 prosim stahnete ty csv soubory a prejmenujte na png, pokud je v tom obrazek, je to stejny problem.

Jak se pise v tom vlakne, zatim nemam reseni.

Na tom RPi to je managed nebo kontejner?

**Comment by jankorous** [comment]
Jj, po přejmenování je to obrázek.

Na RPi mi HA běží jako OS, nic jiného na RPi není.

**Comment by ondrejvysek** [comment]
Toto zaviram, udelal jsem novy bug https://github.com/ondrejvysek/HomeAssistant-CEZDistribuce-PND/issues/43 at se neplete
