### ISSUE TITLE
HTTPS AppDaemon disconnected from Home Assistant, retrying in 5 seconds

### ISSUE THREAD

**Issue by czgif** [ondrejvysek/HomeAssistant-CEZDistribuce-PND#57]
Ahoj, měl jsem problém s AppDaemonem, který hlásil "Disconnected from Home Assistant, retrying in 5 seconds". Jediné, co jsem předtím aktualizoval, byl přechod na HTTPS. Pokud někdo narazí na podobný problém, řešením je přidat řádek cert_verify: false do konfigurace appdaemon.yaml.

Konfigurační soubor bude vypadat takto:

yaml:
appdaemon:
  plugins:
    HASS:
      type: hass
      ha_url: "xxx.xxx.xxx.xxx:8123"
      token: "YOUR_LONG_LIVED_ACCESS_TOKEN"
      cert_verify: false

Snad to někomu pomůže!

**Comment by ondrejvysek** [comment]
Díky za poznatek!
